# Generated by Django 4.2.7 on 2023-11-11 07:46

import apps.docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('app', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to=apps.docs.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
