# Generated by Django 4.2.7 on 2023-11-23 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='app',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
