# Generated by Django 4.2.7 on 2023-11-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='description',
        ),
        migrations.AlterField(
            model_name='fileactivity',
            name='action',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update')], max_length=1),
        ),
        migrations.AlterField(
            model_name='folderactivity',
            name='action',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
