# Generated by Django 4.2.7 on 2023-11-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_remove_file_description_alter_fileactivity_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folderactivity',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folderactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='file',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FileActivity',
        ),
        migrations.DeleteModel(
            name='FolderActivity',
        ),
    ]
