# Generated by Django 4.2.7 on 2023-11-02 16:50

from django.db import migrations, transaction

def create_default_roles(apps, schema_editor):
    
    UserRole = apps.get_model('users', 'UserRole')
    
    with transaction.atomic():
        UserRole.objects.create(role_name='admin')
        UserRole.objects.create(role_name='user')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
