# Generated by Django 4.2.10 on 2024-02-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_team_leader_teamleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_leader_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teamleader'),
        ),
    ]
