# Generated by Django 4.2.10 on 2024-02-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_team_leader_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team_leader_relation',
        ),
    ]
