# Generated by Django 4.2.10 on 2024-03-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_team_leader_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Última Activação'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_inactive',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Última Inactivação'),
        ),
    ]
