# Generated by Django 4.2.10 on 2024-03-12 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_last_active_alter_user_last_inactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('short_desc', models.CharField(max_length=100, verbose_name='short description')),
                ('long_desc', models.CharField(blank=True, max_length=254, null=True, verbose_name='long description')),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'O campo apenas pode conter números.')], verbose_name='Código Status')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=240, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='team_leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkflowConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('LEAD-VENDA', 'Lead - Venda'), ('LEAD-COMPRA', 'Lead - Compra'), ('PROSPECT-VENDA', 'Prospect - Venda'), ('PROSPECT-COMPRA', 'Prospect - Compra')], max_length=20, verbose_name='Tipo Workflow')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('available_if', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_if', to='users.statuscode', verbose_name='Disponível se')),
                ('config_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masterconfig')),
                ('end_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_status', to='users.statuscode', verbose_name='Estado Final')),
                ('start_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_status', to='users.statuscode', verbose_name='Estado Inicial')),
            ],
        ),
        migrations.CreateModel(
            name='StatusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('LEAD', 'Lead'), ('PROSPECT', 'Prospect')], max_length=20, verbose_name='Tipo Status')),
                ('label', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='status_icons')),
                ('tooltip', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('config_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masterconfig')),
                ('status_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.statuscode')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Client')),
                ('nif', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'O campo apenas pode conter números.')], verbose_name='NIF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'O campo apenas pode conter números.')], verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('limit_date', models.DateField(verbose_name='Limit Date')),
                ('logo', models.ImageField(upload_to='license_logos', verbose_name='Logo')),
                ('config_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.masterconfig', verbose_name='configuration id')),
            ],
        ),
    ]
