# Generated by Django 4.2.11 on 2024-03-15 12:33

from django.db import migrations

def create_role(apps, schema_editor):
    UserRole = apps.get_model('users', 'UserRole')
    UserRole.objects.create(role_name='chefe_equipa')
    UserRole.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_masterconfig_statuscode_alter_profile_about_and_more'),
    ]

    operations = [
        migrations.RunPython(create_role),
    ]

