# Generated by Django 4.2.11 on 2024-03-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_config_id_license_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='users.userrole'),
        ),
    ]
