# Generated by Django 4.2.7 on 2023-11-11 08:19

from django.db import migrations

def create_status_desc(apps, schema_editor):
    LeadStatusDesc = apps.get_model('crm', 'LeadStatusDesc')
    LeadStatusDesc.objects.create(desc='New')

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_status_desc),
    ]
