# Generated by Django 4.2.7 on 2023-11-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_clientdoc_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocStatusDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='desc')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
            ],
        ),
        migrations.RenameField(
            model_name='consultantlead',
            old_name='leads',
            new_name='lead',
        ),
        migrations.AddField(
            model_name='client',
            name='email_address',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=16, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultant',
            name='phone_number',
            field=models.CharField(default='', max_length=16, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClientDocStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated on')),
                ('client_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientdoc_status', to='crm.clientdoc', verbose_name='clientdoc')),
                ('doc_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientdocstatus_clientdocstatusdesc', to='crm.clientdocstatusdesc', verbose_name='doc desc')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
        ),
    ]
