# Generated by Django 4.2.10 on 2024-02-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_clientmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
