# Generated by Django 4.2.10 on 2024-03-03 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qaddress', '0001_initial'),
        ('imovel', '0003_imoveltype_imovel_created_at_imovel_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_client_ident_doc_client_nif_client_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='url',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='lead client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='com_tip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='comunication tips'),
        ),
        migrations.AddField(
            model_name='lead',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qaddress.countydata', verbose_name='county'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='lead',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qaddress.districtdata', verbose_name='district'),
        ),
        migrations.AddField(
            model_name='lead',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel', verbose_name='lead imovel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qaddress.cpdata', verbose_name='locality'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='short_desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='lead',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ident_doc',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='identity document'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='NIF'),
        ),
    ]
