# Generated by Django 4.2.10 on 2024-03-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_client_url_remove_lead_email_remove_lead_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='lead type')),
            ],
        ),
    ]
