# Generated by Django 4.2.10 on 2024-02-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_client_ident_doc_remove_client_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ident_doc',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='identity doc'),
        ),
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.CharField(max_length=9, null=True, unique=True, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.CharField(null=True, unique=True, verbose_name='social link'),
        ),
    ]
