# Generated by Django 4.2.10 on 2024-03-03 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_imoveltype_imovel_created_at_imovel_image_and_more'),
        ('qaddress', '0001_initial'),
        ('crm', '0011_leadtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='leadtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lead_type', to='crm.leadtype'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='lead client'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qaddress.countydata', verbose_name='county'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qaddress.districtdata', verbose_name='district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='imovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel', verbose_name='lead imovel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qaddress.cpdata', verbose_name='locality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='short_name',
            field=models.CharField(default=1, max_length=20, verbose_name='short name'),
            preserve_default=False,
        ),
    ]
