# Generated by Django 4.2.11 on 2024-03-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_lead_is_active_alter_lead_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='locality',
        ),
    ]
