# Generated by Django 4.2.11 on 2024-03-17 23:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0014_remove_lead_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='company name')),
                ('phone', models.CharField(max_length=16, verbose_name='phone number')),
                ('logo', models.ImageField(upload_to='media/logos', verbose_name='company logo')),
            ],
        ),
        migrations.AlterField(
            model_name='leaddoc',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead'),
        ),
        migrations.CreateModel(
            name='Prospects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(max_length=100, verbose_name='short description')),
                ('partyname', models.CharField(max_length=100, verbose_name='third party name')),
                ('partyphone', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(900000000), django.core.validators.MaxValueValidator(999999999)])),
                ('partyemail', models.EmailField(max_length=254, verbose_name='third party email')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='comment')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='posted_at')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_license', to='crm.license'),
        ),
        migrations.AddField(
            model_name='lead',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_license', to='crm.license'),
        ),
    ]
