# Generated by Django 4.2.11 on 2024-03-18 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_license_alter_leaddoc_lead_prospects_leadcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='license',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_license', to='crm.license'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='license',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_license', to='crm.license'),
        ),
    ]
