# Generated by Django 4.2.11 on 2024-03-19 12:49

import apps.users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_config_id_license_config_and_more'),
        ('crm', '0017_remove_leadstatus_lead_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatus',
            name='status',
            field=models.ForeignKey(default=apps.users.models.StatusCode.get_default, on_delete=django.db.models.deletion.CASCADE, related_name='status_code', to='users.statuscode', verbose_name='status'),
        ),
    ]
