# Generated by Django 4.2.11 on 2024-04-02 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0020_alter_prospects_partyphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='comment')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='posted_at')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.prospects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
