# Generated by Django 4.2.11 on 2024-04-03 14:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0021_prospectscomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prospects',
            new_name='Prospect',
        ),
        migrations.RenameModel(
            old_name='ProspectsComment',
            new_name='ProspectComment',
        ),
    ]
