# Generated by Django 4.2.11 on 2024-04-03 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0022_rename_prospects_prospect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='createdby_prospect', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospect',
            name='house_desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='house_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='in_percent',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='prospect',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_prospect', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
