# Generated by Django 4.2.7 on 2023-11-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_clientdoc_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('bedrooms', models.IntegerField(verbose_name='bedrooms')),
                ('bathrooms', models.IntegerField(verbose_name='bathrooms')),
                ('square_footage', models.IntegerField(verbose_name='square footage')),
            ],
        ),
        migrations.CreateModel(
            name='ImovelLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='ImovelDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='token')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
            ],
        ),
    ]
