# Generated by Django 4.2.10 on 2024-02-29 18:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_imoveldocstatusdesc_imoveldoc_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='image',
            field=models.ImageField(blank=True, upload_to='imovel_pics', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='imovel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imovel.imoveltype'),
        ),
    ]
