# Generated by Django 4.2.11 on 2024-03-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_license'),
        ('imovel', '0003_imoveltype_imovel_created_at_imovel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='license',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imovel_license', to='users.license'),
        ),
    ]
