# Generated by Django 4.2.11 on 2024-03-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0004_imovel_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='license',
        ),
    ]
